---
- name: Install PHP and modules
  dnf:
    name:
      - php
      - php-mysqlnd
      - php-cli
      - php-common
    state: present

- name: Restart Apache for PHP
  service:
    name: httpd
    state: restarted
  when: ansible_facts['os_family'] == "RedHat"
