- name: Install PHP
  dnf:
    name:
      - php
      - php-mysqlnd
      - php-cli
      - php-common
    state: present

- name: Create PHP info page
  copy:
    content: "<?php phpinfo(); ?>"
    dest: "{{ doc_root }}/index.php"
    owner: apache
    group: apache
    mode: '0644'